# This pod runs the ssoconfig image which will
# Configure two AM instances in a cluster
# Wait until the AM instances are up before running this
#
apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: ssoconfig
  name: ssoconfig
spec:
    containers:
    - name: openam-a
      image: wstrange/ssoconfig:latest